name: 部署博客到W3存储
on:
  push:
    branches:
      - main

# 定义工作流阶段
jobs:
  build-and-deploy:
    name: 构建并部署博客1
    runs-on: ubuntu-latest
    steps:
      # 检出代码 - 使用内置的检出操作，不依赖外部 actions
      - name: 检出代码
        uses: actions/checkout:https://github.com/actions/checkout
        # with:
        #   fetch-depth: 0 # 获取完整历史以便 git 命令正常工作

      # 构建 Docker 镜像并运行
      - name: 构建并运行 Docker 镜像
        run: |
          echo "构建 Docker 镜像..."
          # 确保 Dockerfile 中已添加 git 和 openssh
          docker build -t vitepress-blog .

          # 创建目录以确保挂载点存在
          mkdir -p /github/workspace/docs/.vitepress/dist

          # 清理可能存在的旧容器
          echo "清理可能存在的旧容器..."
          docker rm -f vitepress-builder || true

          # 运行容器并挂载卷
          echo "运行容器并构建博客..."
          docker run --name vitepress-builder \
            -v /github/workspace:/github/workspace \
            -v /github/workspace/docs/.vitepress/dist:/app/docs/.vitepress/dist \
            vitepress-blog

          # 检查构建结果
          echo "检查构建结果..."
          ls -la /github/workspace/docs/.vitepress/dist || echo "构建目录不存在"

      # 安装 AWS CLI
      - name: 安装 AWS CLI
        run: |
          echo "安装 AWS CLI..."
          # 使用国内镜像源加速 apt 更新
          sed -i 's/archive.ubuntu.com/mirrors.ustc.edu.cn/g' /etc/apt/sources.list
          sed -i 's/security.ubuntu.com/mirrors.ustc.edu.cn/g' /etc/apt/sources.list
          apt-get update && apt-get install -y curl unzip

          # 使用阿里云 OSS 镜像下载 AWS CLI
          echo "从国内镜像下载 AWS CLI..."
          curl "https://gosspublic.alicdn.com/ossutil/awscli-bundle.zip" -o "awscli-bundle.zip" --connect-timeout 30 --retry 5 --retry-delay 2 || \
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscli-bundle.zip" --connect-timeout 30 --retry 5 --retry-delay 2

          unzip -q awscli-bundle.zip
          ./aws/install || ./awscli-bundle/install -i /usr/local/aws-cli -b /usr/local/bin/aws
          aws --version

      # 配置 AWS
      - name: 配置 AWS
        run: |
          echo "配置 AWS 凭证..."
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws configure set output json
          aws configure set default.s3.addressing_style path
          aws configure set default.s3.payload_signing_enabled true

      # 上传到 S3
      - name: 上传到 W3 存储
        run: |
          echo "上传到 W3 存储..."
          aws s3 cp /github/workspace/docs/.vitepress/dist s3://115-web/blog/ \
            --recursive \
            --cache-control "max-age=3600" \
            --endpoint-url http://home.yuanquanke.cn:35246

      # 清理资源
      - name: 清理资源
        if: always() # 无论前面步骤成功或失败，都执行清理
        run: |
          echo "清理资源..."
          docker rm -f vitepress-builder || true

      # 部署完成通知
      - name: 部署完成通知
        if: success() # 仅在成功时显示
        run: |
          echo "✅ 博客已成功部署到 W3 存储！"
          echo "📊 部署时间: $(date)"
          echo "🌐 访问地址: http://home.yuanquanke.cn:35246/115-web/blog/index.html"
