name: éƒ¨ç½²åšå®¢åˆ°W3å­˜å‚¨
on:
  push:
    branches:
      - main

# å®šä¹‰å·¥ä½œæµé˜¶æ®µ
jobs:
  build-and-deploy:
    name: æž„å»ºå¹¶éƒ¨ç½²åšå®¢
    runs-on: ubuntu-latest
    steps:
      # æ£€å‡ºä»£ç  - ä½¿ç”¨å†…ç½®çš„æ£€å‡ºæ“ä½œï¼Œä¸ä¾èµ–å¤–éƒ¨ actions
      - name: æ£€å‡ºä»£ç 
        uses: actions/checkout@v4:https://github.com/actions/checkout
        with:
          fetch-depth: 0 # èŽ·å–å®Œæ•´åŽ†å²ä»¥ä¾¿ git å‘½ä»¤æ­£å¸¸å·¥ä½œ

      # æž„å»º Docker é•œåƒå¹¶è¿è¡Œ
      - name: æž„å»ºå¹¶è¿è¡Œ Docker é•œåƒ
        run: |
          echo "æž„å»º Docker é•œåƒ..."
          # ç¡®ä¿ Dockerfile ä¸­å·²æ·»åŠ  git å’Œ openssh
          docker build -t vitepress-blog .

          # åˆ›å»ºç›®å½•ä»¥ç¡®ä¿æŒ‚è½½ç‚¹å­˜åœ¨
          mkdir -p /share/CACHEDEV1_DATA/Container/gitea/deploy/blog/dist

          # æ¸…ç†å¯èƒ½å­˜åœ¨çš„æ—§å®¹å™¨
          echo "æ¸…ç†å¯èƒ½å­˜åœ¨çš„æ—§å®¹å™¨..."
          docker rm -f vitepress-builder || true

          # è¿è¡Œå®¹å™¨å¹¶æŒ‚è½½å·
          echo "è¿è¡Œå®¹å™¨å¹¶æž„å»ºåšå®¢..."
          docker run --name vitepress-builder \
            -v /share/CACHEDEV1_DATA/Container/gitea/deploy/blog/dist:/app/docs/.vitepress/dist \
            vitepress-blog

          # æ£€æŸ¥æž„å»ºç»“æžœ 1
          echo "æ£€æŸ¥æž„å»ºç»“æžœ..."
          ls -la /share/CACHEDEV1_DATA/Container/gitea/deploy/blog/dist || echo "æž„å»ºç›®å½•ä¸å­˜åœ¨"

      # ä½¿ç”¨ Docker è¿è¡Œ AWS CLI
      - name: ä½¿ç”¨ Docker è¿è¡Œ AWS CLI
        run: |
          echo "æ‹‰å– AWS CLI Docker é•œåƒ..."
          # æ‹‰å– AWS CLI å®˜æ–¹ Docker é•œåƒ
          docker pull public.ecr.aws/aws-cli/aws-cli:latest || \
          docker pull amazon/aws-cli:latest || \
          echo "AWS CLI Docker é•œåƒæ‹‰å–å¤±è´¥ï¼Œä½†ç»§ç»­æ‰§è¡Œ"

          # åˆ›å»º AWS é…ç½®ç›®å½•
          mkdir -p ~/.aws

          # é…ç½® AWS å‡­è¯
          echo "é…ç½® AWS å‡­è¯..."
          cat > ~/.aws/credentials << EOF
          [default]
          aws_access_key_id = ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key = ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          EOF

          # é…ç½® AWS è®¾ç½®
          cat > ~/.aws/config << EOF
          [default]
          output = json
          s3 =
              addressing_style = path
              payload_signing_enabled = true
          EOF

          # ä½¿ç”¨ Docker è¿è¡Œ AWS CLI ä¸Šä¼ æ–‡ä»¶
          echo "ä¸Šä¼ åˆ° W3 å­˜å‚¨..."
          docker run --rm \
            -v ~/.aws:/root/.aws \
            -v /share/CACHEDEV1_DATA/Container/gitea/deploy/blog/dist:/aws/dist \
            public.ecr.aws/aws-cli/aws-cli:latest s3 cp /aws/dist s3://115-web/blog/ \
            --recursive \
            --cache-control "max-age=3600" \
            --endpoint-url http://home.yuanquanke.cn:35246 || \
          docker run --rm \
            -v ~/.aws:/root/.aws \
            -v /share/CACHEDEV1_DATA/Container/gitea/deploy/blog/dist:/aws/dist \
            amazon/aws-cli:latest s3 cp /aws/dist s3://115-web/blog/ \
            --recursive \
            --cache-control "max-age=3600" \
            --endpoint-url http://home.yuanquanke.cn:35246

      # æ¸…ç†èµ„æº
      - name: æ¸…ç†èµ„æº
        if: always() # æ— è®ºå‰é¢æ­¥éª¤æˆåŠŸæˆ–å¤±è´¥ï¼Œéƒ½æ‰§è¡Œæ¸…ç†
        run: |
          echo "æ¸…ç†èµ„æº..."
          docker rm -f vitepress-builder || true
          rm -rf /share/CACHEDEV1_DATA/Container/gitea/deploy/blog/dist

      # éƒ¨ç½²å®Œæˆé€šçŸ¥
      - name: éƒ¨ç½²å®Œæˆé€šçŸ¥
        if: success() # ä»…åœ¨æˆåŠŸæ—¶æ˜¾ç¤º
        run: |
          echo "âœ… åšå®¢å·²æˆåŠŸéƒ¨ç½²åˆ° W3 å­˜å‚¨ï¼"
          echo "ðŸ“Š éƒ¨ç½²æ—¶é—´: $(date)"
          echo "ðŸŒ è®¿é—®åœ°å€: http://home.yuanquanke.cn:35246/115-web/blog/index.html"
