name: 部署博客到W3存储
on:
  push:
    branches:
      - main

# 定义工作流阶段
jobs:
  build-and-deploy:
    name: 构建并部署博客
    runs-on: ubuntu-latest
    # 使用 Docker 容器
    container:
      image: node:22-alpine
      options: --user root
    steps:
      # 检出代码
      - name: 检出代码
        uses: actions/checkout@v4

      # 安装必要的系统依赖
      - name: 安装系统依赖
        run: |
          echo "安装系统依赖..."
          apk update && apk add --no-cache git python3 py3-pip curl wget
          pip3 install awscli
          aws --version

      # 安装 pnpm
      - name: 安装 pnpm
        run: |
          npm install -g pnpm@latest --registry=https://registry.npmmirror.com
          pnpm config set registry https://registry.npmmirror.com
          pnpm --version

      # 安装依赖（使用缓存提高构建速度）
      - name: 安装依赖
        run: |
          echo "安装项目依赖..."
          pnpm install
          # 安装 pagefind 用于站内搜索
          pnpm add pagefind -D

      # 构建博客
      - name: 构建博客
        run: |
          echo "开始构建博客..."
          pnpm build
          echo "博客构建完成！"
          ls -la docs/.vitepress/dist

      # 配置上传脚本
      - name: 准备上传脚本
        run: |
          echo "准备上传脚本..."
          chmod +x ./upload-to-w3.sh
          
      # 配置 AWS 并部署
      - name: 配置 AWS 并部署
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          DIST_DIR: /github/workspace/docs/.vitepress/dist
          S3_BUCKET: 115-web
          S3_PREFIX: blog/
          S3_ENDPOINT: http://home.yuanquanke.cn:35246
        run: |
          echo "配置 AWS 凭证并开始部署..."
          # 配置 AWS CLI
          aws configure set default.s3.addressing_style path
          aws configure set default.s3.payload_signing_enabled true
          
          # 执行上传
          echo "正在部署博客到 W3 存储..."
          aws s3 sync "$DIST_DIR/" "s3://$S3_BUCKET/$S3_PREFIX" \
            --delete \
            --cache-control "max-age=3600" \
            --endpoint-url "$S3_ENDPOINT"

      # 部署完成通知
      - name: 部署完成通知
        run: |
          echo "✅ 博客已成功部署到 W3 存储！"
          echo "📊 部署时间: $(date)"
          echo "🌐 访问地址: http://home.yuanquanke.cn:35246/115-web/blog/index.html"
