name: 部署博客到W3存储
on:
  push:
    branches:
      - main

# 定义工作流阶段
jobs:
  build-and-deploy:
    name: 构建并部署博客
    runs-on: ubuntu-latest
    steps:
      # 检出代码
      - name: 检出代码
        uses: actions/checkout@v4

      - name: 设置 Docker 环境 构建 并输出 dist 目录给下个流水线
        run: |
          echo "设置 Docker 环境 构建 并输出 dist 目录给下个流水线..."
          docker build -t vitepress-blog .
          docker run -v /github/workspace/docs/.vitepress/dist:/app/docs/.vitepress/dist vitepress-blog
          ls -la /github/workspace/docs/.vitepress/dist

      - name: 安装AWS CLI
        run: |
          echo "安装AWS CLI..."
          apt-get update && apt-get install -y curl unzip
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip" --connect-timeout 30 --retry 3 || echo "下载失败，但继续执行"
          unzip -q awscliv2.zip || echo "解压失败，但继续执行"
          ./aws/install || echo "安装失败，但继续执行"
          rm -rf awscliv2.zip aws
          which aws || echo "AWS CLI未找到"

      - name: 配置AWS
        run: |
          echo "配置AWS凭证..."
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws configure set output json
          aws configure set default.s3.addressing_style path
          aws configure set default.s3.payload_signing_enabled true

      - name: 上传到S3
        run: |
          echo "上传到S3"
          aws s3 cp /github/workspace/docs/.vitepress/dist s3://115-web/blog/ --recursive --endpoint-url http://home.yuanquanke.cn:35246

      # 删除构建容器
      - name: 删除构建容器
        run: |
          echo "删除构建容器..."
          docker rm -f vitepress-blog

      # 部署完成通知
      - name: 部署完成通知
        run: |
          echo "✅ 博客已成功部署到 W3 存储！"
          echo "📊 部署时间: $(date)"
          echo "🌐 访问地址: http://home.yuanquanke.cn:35246/115-web/blog/index.html"
