name: 部署博客到S3
on:
  push:
    branches:
      - main

# 定义工作流阶段
jobs:
  build-and-deploy:
    name: 构建并部署博客
    runs-on: ubuntu-latest
    # 使用 Docker 容器
    container:
      image: node:22-alpine
      options: --user root
    steps:
      # 检出代码
      - name: 检出代码
        run: |
          echo "手动检出代码..."
          git clone https://gitea.com/${{ github.repository }}.git .
          git checkout ${{ github.sha }}

      # 安装必要的系统依赖
      - name: 安装系统依赖
        run: |
          echo "安装 git 和其他必要的工具..."
          apk add --no-cache git
      
      # 安装 pnpm
      - name: 安装 pnpm
        run: |
          npm install -g pnpm@latest --registry=https://registry.npmmirror.com
          pnpm config set registry https://registry.npmmirror.com
          pnpm --version

      # 安装依赖
      - name: 安装依赖
        run: |
          echo "安装项目依赖..."
          pnpm install
          # 如果构建时间过长，可以手动安装 pagefind
          pnpm add pagefind -D

      # 构建博客
      - name: 构建博客
        run: |
          pnpm build
          echo "博客构建完成！"
          ls -la docs/.vitepress/dist

      # 安装 AWS CLI
      - name: 安装 AWS CLI
        run: |
          echo "安装 AWS CLI..."
          # Alpine环境下安装AWS CLI
          apk add --no-cache python3 py3-pip curl
          pip3 install awscli
          aws --version || echo "AWS CLI未找到"

      - name: 配置 AWS
        run: |
          echo "配置 AWS 凭证..."
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws configure set output json
          aws configure set default.s3.addressing_style path
          aws configure set default.s3.payload_signing_enabled true

      - name: 部署到 S3
        run: |
          echo "正在部署博客到 S3..."
          # 使用 --delete 参数删除目标位置上已经不存在于源位置的文件
          # 使用 --cache-control 参数设置缓存控制
          aws s3 sync docs/.vitepress/dist/ s3://115-web/blog/ \
            --delete \
            --cache-control "max-age=3600" \
            --endpoint-url http://home.yuanquanke.cn:35246

      - name: 部署完成通知
        run: |
          echo "博客已成功部署到 S3！"
          echo "访问地址: http://home.yuanquanke.cn:35246/115-web/blog/index.html"
