name: éƒ¨ç½²åšå®¢åˆ°W3å­˜å‚¨
on:
  push:
    branches:
      - main

# å®šä¹‰å·¥ä½œæµé˜¶æ®µ
jobs:
  build-and-deploy:
    name: æž„å»ºå¹¶éƒ¨ç½²åšå®¢
    runs-on: ubuntu-latest
    steps:
      # æ£€å‡ºä»£ç  - ä½¿ç”¨å†…ç½®çš„æ£€å‡ºæ“ä½œï¼Œä¸ä¾èµ–å¤–éƒ¨ actions
      - name: æ£€å‡ºä»£ç 
        uses: actions/checkout@v4:https://github.com/actions/checkout
        with:
          fetch-depth: 0 # èŽ·å–å®Œæ•´åŽ†å²ä»¥ä¾¿ git å‘½ä»¤æ­£å¸¸å·¥ä½œ

      # è®¾ç½® Node.js çŽ¯å¢ƒ
      - name: è®¾ç½® Node.js çŽ¯å¢ƒ
        run: |
          echo "è®¾ç½® Node.js çŽ¯å¢ƒ..."
          # æ£€æŸ¥ Node.js ç‰ˆæœ¬
          node --version
          npm --version

          # å®‰è£… pnpm
          echo "å®‰è£… pnpm..."
          npm install -g pnpm
          pnpm --version

      # å®‰è£…ä¾èµ–å¹¶æž„å»º
      - name: å®‰è£…ä¾èµ–å¹¶æž„å»º
        run: |
          echo "å®‰è£…é¡¹ç›®ä¾èµ–..."
          # ä½¿ç”¨å›½å†…é•œåƒæºåŠ é€Ÿå®‰è£…
          pnpm config set registry https://registry.npmmirror.com
          pnpm install

          echo "æž„å»ºåšå®¢..."
          pnpm build

          # æ£€æŸ¥æž„å»ºç»“æžœ
          echo "æ£€æŸ¥æž„å»ºç»“æžœ..."
          ls -la docs/.vitepress/dist || echo "æž„å»ºç›®å½•ä¸å­˜åœ¨"

      # ä½¿ç”¨ Docker è¿è¡Œ AWS CLI
      - name: ä½¿ç”¨ Docker è¿è¡Œ AWS CLI
        run: |
          echo "æ‹‰å– AWS CLI Docker é•œåƒ..."
          # æ‹‰å– AWS CLI å®˜æ–¹ Docker é•œåƒ
          docker pull amazon/aws-cli || echo "AWS CLI Docker é•œåƒæ‹‰å–å¤±è´¥ï¼Œä½†ç»§ç»­æ‰§è¡Œ"

          # åˆ›å»º AWS é…ç½®ç›®å½•
          mkdir -p ~/.aws

          # é…ç½® AWS å‡­è¯
          echo "é…ç½® AWS å‡­è¯..."
          cat > ~/.aws/credentials << EOF
          [default]
          aws_access_key_id = ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key = ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          EOF

          # é…ç½® AWS è®¾ç½® 1
          cat > ~/.aws/config << EOF
          [default]
          output = json
          s3 =
              addressing_style = path
              payload_signing_enabled = true
          EOF

          echo "AWS å‡­è¯å’Œé…ç½®æ–‡ä»¶å†…å®¹..."
          cat ~/.aws/credentials
          cat ~/.aws/config

          # èŽ·å–å½“å‰å·¥ä½œç›®å½•çš„ç»å¯¹è·¯å¾„
          WORKSPACE_DIR=$(pwd)
          echo "å½“å‰å·¥ä½œç›®å½•: $WORKSPACE_DIR"

          # ç¡®ä¿æž„å»ºç›®å½•å­˜åœ¨
          echo "æ£€æŸ¥æž„å»ºç›®å½•..."
          ls -la $WORKSPACE_DIR/docs/.vitepress/dist || echo "æž„å»ºç›®å½•ä¸å­˜åœ¨"


          # ä½¿ç”¨ Docker è¿è¡Œ AWS CLI ä¸Šä¼ æ–‡ä»¶ å¿—å®žæ—¶è¾“å‡ºåˆ°æŽ§åˆ¶å°
          echo "ä¸Šä¼ åˆ° W3 å­˜å‚¨..."
           docker run --rm \
           --name aws-cli \
            -v ~/.aws:/root/.aws \
            -v $WORKSPACE_DIR/docs/.vitepress/dist:/aws/dist \
            amazon/aws-cli s3 cp . s3://115-web/blog/ \
            --recursive \
            --cache-control "max-age=3600" \
            --endpoint-url http://home.yuanquanke.cn:35246

      # æ¸…ç†èµ„æº
      # - name: æ¸…ç†èµ„æº
      #   if: always() # æ— è®ºå‰é¢æ­¥éª¤æˆåŠŸæˆ–å¤±è´¥ï¼Œéƒ½æ‰§è¡Œæ¸…ç†
      #   run: |
      #     echo "æ¸…ç†èµ„æº..."
      #     rm -rf $WORKSPACE_DIR/docs/.vitepress/dist

      # éƒ¨ç½²å®Œæˆé€šçŸ¥
      - name: éƒ¨ç½²å®Œæˆé€šçŸ¥
        if: success() # ä»…åœ¨æˆåŠŸæ—¶æ˜¾ç¤º
        run: |
          echo "âœ… åšå®¢å·²æˆåŠŸéƒ¨ç½²åˆ° W3 å­˜å‚¨ï¼"
          echo "ðŸ“Š éƒ¨ç½²æ—¶é—´: $(date)"
          echo "ðŸŒ è®¿é—®åœ°å€: http://home.yuanquanke.cn:35246/115-web/blog/index.html"
